### ISSUE TITLE
Sonarr v3 Error regarding LanguageId

### ISSUE THREAD

**Issue by Procuria** [Kometa-Team/Kometa#1249]
### Version Number

Version: 1.18.1 (Docker)

### What branch are you on?

nightly

### Describe the Bug

Sonarr Version: 3.0.9.1549

When running the "Sonarr part" of my TV-library I hit  the following error:

`Sonarr Error: (500 [Internal Server Error]) {'message': 'Unexpected character encountered while parsing value: [. Path \'[0].languageProfileId\', line 1, position 1576. (Json snippet \'anguageProfileId": [<--error-->1], "seasonFolder": \')', 'description': 'Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path \'[0].languageProfileId\', line 1, position 1576. (Json snippet \'anguageProfileId": [<--error-->1], "seasonFolder": \') `

It seems that the languageID isn't parsed correctly.

I run the latest nightly docker image - build today [29.12] via _not modified_ Dockerfile.

### Relevant Collection/Overlay/Playlist Definition

```yml
sonarr:                          
      url: https://redacted.for.privacy/sonarr
      token: redacted.for.privacy
      add_missing: true
      add_existing: false
      root_folder_path: /home/media/tv
      monitor: all
      quality_profile: Series High Quality
      language_profile: English
      series_type: standard
      season_folder: true
      tag: pmm
      search: true
      cutoff_search: false
      sonarr_path:
      plex_path:
```

### Logs

https://gist.github.com/Procuria/4e508853fbae7f9bebbc2d07da5cdd65#file-sonarr_error_log-md

**Comment by Procuria** [comment]
I think the above described issue is caused by the issue [Type "anguageid" instead of languageid #15 ](https://github.com/meisnate12/ArrAPI/issues/15#issue-1510727504) over in the **ArrAPI repo**.

**Comment by meisnate12** [comment]
this should already be fixed in nightly

**Comment by Procuria** [comment]
@meisnate12 unfortunately the issue still persists. Just ran a test with 1.4.2 and still getting this error.
As I don't speak Python and just being able to read it a bit I'm wondering how I could contribute to the troubleshooting.
My best guess is, that something happens in the transformation to the JSON payload for the Sonarr request, which "cuts away" the L in LanguageID.

Is there any additional information I can provide?
<img width="658" alt="2022-12-31_13h06_04" src="https://user-images.githubusercontent.com/37988494/210138509-d1f888be-d58c-42ef-8d3d-c43c48f0ac37.png">

**Comment by Procuria** [comment]
@meisnate12  I'm honestly sorry for creating this fuzz. As you said, the **error is resolved in nightly** 
I had my CI/CD pipeline misconfigured - the nightly image was build but not deployed. 😞 

Thank you for your awesome work and have a healthy start of the new orbit of the sun.
