### ISSUE TITLE
[Defaults]: The language code for the Philippines is tgl or tl which stands for Tagalog. 

### ISSUE THREAD

**Issue by ChristianStrawn** [Kometa-Team/Kometa#1490]
### Link to File

Plex-Meta-Manager/defaults/overlays/languages.yml

### Version Number

1.19.0 

### What branch are you on?

master

### Describe the Bug

There is no "fl" in the List of ISO 639-1 https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes so the "fl" in the [wiki Overlays](https://metamanager.wiki/en/latest/defaults/overlays/languages.html) page might be wrong.

I can't get the Philippine flag to appear when applying the overlays, even with tgl = tagalog or fil = filipino language tags on the MKV. I also made sure to add "fl" to the template_variables.

**Comment by bullmoose20** [comment]
Would you mind joining us on the discord for PMM so that we can actively troubleshoot this please? I think there might be a mistake as well however I do not have any media items that have audio or subtitles in Filipino… so I don’t know the best way to resolve this at the moment. This yml is not looking at filename when creating the overlay so adding the code to the filename won’t help. We need to see the meta.log showing that it is looking for a file and that file is missing from our repo.

**Comment by bullmoose20** [comment]
FYI, submitted a yml change to change fl to tl. This should resolve the issue you are facing

**Comment by ChristianStrawn** [comment]
> FYI, submitted a yml change to change fl to tl. This should resolve the issue you are facing

Oh thank you! I was about to hop on discord. That's awesome! cheers.

**Comment by YozoraXCII** [comment]
This should be resolved in the nightly branch

**Comment by ChristianMalazarte** [comment]
I tried running the nightly but it seems this is the output still:
```
| Validating Method: plex_search                                                                     
| Value: {'all': {'audio_language': 'fl'}} 
```

**Comment by ChristianStrawn** [comment]
I still can't get the filipino flag to show up :(

Looks like even if the audio language code in the video is tgl or tl (tagalog), plex will interpret it as fil. Just tried nightly branch and no go.

```
| Validating Method: overlay                                                                         |
| Value: {'name': 'text(FL)', 'pmm': 'flag/square/ph', 'queue': 'flags', 'weight': 270, 'font': 'fonts/Inter-Bold.ttf', 'font_size': 50, 'font_color': '#FFFFFF', 'back_color': '#00000099', 'back_width': 190, 'back_align': 'left', 'addon_offset': 10, 'addon_position': 'left'} |
|                                                                                                    |
| Validating Method: ignore_blank_results                                                            |
| Value: True                                                                                        |
|                                                                                                    |
| Validating Method: plex_search                                                                     |
| Value: {'all': {'audio_language': 'tl'}} 
```
This screenshot is from the media info in Plex:
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/100416221/20e3ed0c-33b5-4a5f-9d29-f2f35c3baa36)

**Comment by ChristianStrawn** [comment]
It looks like the PMM Wiki was updated, and "fil" was added! I'm trying it now!

https://metamanager.wiki/en/latest/defaults/overlays/languages.html#supported-audio-subtitle-language-flags

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/100416221/9ab68fde-6ddf-49c8-ac99-1f8867b34fa5)

**Comment by ChristianStrawn** [comment]
Still no go. I just read the PMM logs and it's skipping the "fil" language code even tho I added "fil" in my template_variables: languages: in the config.yml

```
    - pmm: languages
      template_variables:
        languages: [en, de, fr, es, pt, ja, ko, zh, da, ru, it, hi, te, fa, th, nl,
          no, is, sv, tr, pl, cs, uk, hu, ar, bg, bn, bs, ca, cy, el, et, eu, fi,
          fl, gl, he, hr, id, ka, kk, kn, la, lt, lv, mk, ml, mr, ms, nb, nn, pa,
          ro, sk, sl, sq, sr, sw, tg, ta, ur, vi, tl, fil]
```

**Comment by ChristianStrawn** [comment]
I didn't update docker... lol I'm so stupid! It works now! Thanks to bullmoose for taking the time to help!
