### ISSUE TITLE
Error with item_episode_ordering

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#228]
[Wiki page](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Collection-Details#item-metadata-attributes)

Using:
```
    item_episode_ordering: tvdb_aired
```

Results in this error:
```
[2021-05-04 02:47:15,298] [builder.py:419]            [DEBUG]    | Validating Method: item_episode_ordering                                                           |
[2021-05-04 02:47:15,298] [builder.py:420]            [DEBUG]    | Value: tvdb_aired                                                                                  |

[2021-05-04 02:25:46,951] [plex.py:623]               [DEBUG]    | Details Update: {'showOrdering': 'airing'}                                                         |
[2021-05-04 02:25:47,264] [util.py:313]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/config.py", line 624, in run_collection
                                                                 |     builder.update_details(plex_collection)
                                                                 |   File "/modules/builder.py", line 1283, in update_details
                                                                 |     self.library.edit_item(item, item.title, "Movie" if self.library.is_movie else "Show", advance_edits, advanced=True)
                                                                 |   File "/modules/plex.py", line 626, in edit_item
                                                                 |     item.editAdvanced(**edits)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/mixins.py", line 48, in editAdvanced
                                                                 |     raise NotFound('%s not found in %s' % (value, enumValues))
                                                                 | plexapi.exceptions.NotFound: airing not found in ['', 'tmdbAiring', 'aired', 'dvd', 'absolute']
                                                                 | 
[2021-05-04 02:25:47,264] [config.py:631]             [ERROR]    | Unknown Error: airing not found in ['', 'tmdbAiring', 'aired', 'dvd', 'absolute']
[2021-05-04 02:25:47,264] [config.py:565]             [INFO]     | 
```

I also tried changing it to this based on the error message:
```
    item_episode_ordering: aired
```

which resulted in this error:
```
[2021-05-04 02:45:22,879] [builder.py:419]            [DEBUG]    | Validating Method: item_episode_ordering                                                           |
[2021-05-04 02:45:22,879] [builder.py:420]            [DEBUG]    | Value: aired                                                                                       |
[2021-05-04 02:45:22,879] [builder.py:525]            [ERROR]    | Metadata Error: aired item_episode_ordering attribute invalid                                      |

```

**Comment by meisnate12** [comment]
fixed in develop

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Still getting this error. Looks like the same error, but I didn't look too closely

```
[2021-05-05 02:20:20,128] [builder.py:419]            [DEBUG]    | Validating Method: item_episode_ordering                                                           |
[2021-05-05 02:20:20,128] [builder.py:420]            [DEBUG]    | Value: tvdb_aired   
_______________________________________________________________________________________________

2021-05-05 02:20:21,865] [builder.py:1201]           [INFO]     | Detail: summary updated Collection Summary                                                         |
[2021-05-05 02:20:22,548] [plex.py:623]               [DEBUG]    | Details Update: {'showOrdering': 'airing'}                                                         |
[2021-05-05 02:20:22,832] [util.py:313]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/config.py", line 624, in run_collection
                                                                 |     builder.update_details(plex_collection)
                                                                 |   File "/modules/builder.py", line 1283, in update_details
                                                                 |     self.library.edit_item(item, item.title, "Movie" if self.library.is_movie else "Show", advance_edits, advanced=True)
                                                                 |   File "/modules/plex.py", line 626, in edit_item
                                                                 |     item.editAdvanced(**edits)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/mixins.py", line 48, in editAdvanced
                                                                 |     raise NotFound('%s not found in %s' % (value, enumValues))
                                                                 | plexapi.exceptions.NotFound: airing not found in ['', 'tmdbAiring', 'aired', 'dvd', 'absolute']
                                                                 | 
[2021-05-05 02:20:22,832] [config.py:631]             [ERROR]    | Unknown Error: airing not found in ['', 'tmdbAiring', 'aired', 'dvd', 'absolute']
```

**Comment by meisnate12** [comment]
different error actually lol but its fix in develop

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
```
[2021-05-05 18:06:56,818] [builder.py:1201]           [INFO]     | Detail: summary updated Collection Summary                                                         |
[2021-05-05 18:06:57,481] [util.py:313]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/modules/config.py", line 631, in run_collection
                                                                 |     builder.update_details(plex_collection)
                                                                 |   File "/modules/builder.py", line 1281, in update_details
                                                                 |     if getattr(item, key) != options[method_data]:
                                                                 | KeyError: 'aired'
                                                                 | 
[2021-05-05 18:06:57,481] [config.py:638]             [ERROR]    | Unknown Error: 'aired'
```

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
> ```
> [2021-05-05 18:06:56,818] [builder.py:1201]           [INFO]     | Detail: summary updated Collection Summary                                                         |
> [2021-05-05 18:06:57,481] [util.py:313]               [DEBUG]    | Traceback (most recent call last):                                                                 |
>                                                                  |   File "/modules/config.py", line 631, in run_collection
>                                                                  |     builder.update_details(plex_collection)
>                                                                  |   File "/modules/builder.py", line 1281, in update_details
>                                                                  |     if getattr(item, key) != options[method_data]:
>                                                                  | KeyError: 'aired'
>                                                                  | 
> [2021-05-05 18:06:57,481] [config.py:638]             [ERROR]    | Unknown Error: 'aired'
> ```

@meisnate12 Did you see this error?

**Comment by meisnate12** [comment]
Nope missed this one thanks for following up I'll check it out later today when I get some time

**Comment by meisnate12** [comment]
fix should be in develop
