### ISSUE TITLE
Tv show episode doesn't get an overlay score

### ISSUE THREAD

**Issue by rafapirotto** [Kometa-Team/Kometa#2291]
### Version Number

Version: 2.0.2 (Docker: master)

### What branch are you on?

master

### Describe the Bug

For some reason the last episode of the second season of "Tell me lies" doesn't get an imdb score overlay. I've noticed that the other episodes get updated but this last one has never got a score overlay.
<img width="837" alt="image" src="https://github.com/user-attachments/assets/c563db3a-d0b3-4877-8830-58a4bb300a3f">
<img width="887" alt="image" src="https://github.com/user-attachments/assets/c45691dd-7cfb-4d51-95b0-3369e1b4718b">

I've checked the imdb page and it has always had a score

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  Movies:
    reapply_overlays: true
    remove_overlays: false
    collection_files:
    - folder: collections/movies
    - folder: collections/common
    - default: golden
      template_variables:
        use_year_collections: false
        use_best_picture: true
        use_best_director: true
        collection_order: release.desc
    - default: oscars
      template_variables:
        use_year_collections: false
        use_best_picture: true
        use_best_director: true
        collection_order: release.desc
    - default: cannes
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: bafta
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: sundance
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    - default: venice
      template_variables:
        use_year_collections: false
        collection_order: release.desc
    overlay_files:
    - folder: overlays/common
    - default: runtimes
      template_variables:
        vertical_align: bottom
        horizontal_align: center
    - default: ribbon
      template_variables:
        use_imdb: false
        use_rotten: false
        use_metacritic: false
        use_common: false
    - default: ratings
      template_variables:
        rating1: critic
        rating1_image: rt_tomato
        rating2: audience
        rating2_image: rt_popcorn
        rating3: user
        rating3_image: imdb
    operations:
      mass_user_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_critic_rating_update: mdb_tomatoes
      split_duplicates: true
  TV Shows:
    reapply_overlays: true
    remove_overlays: false
    collection_files:
    - folder: collections/common
    - default: golden
      template_variables:
        use_year_collections: false
        use_best_picture: true
        use_best_director: true
        collection_order: release.desc
    - default: emmy
      template_variables:
        use_year_collections: false
        use_best_picture: true
        use_best_director: true
        collection_order: release.desc
    overlay_files:
    - folder: overlays/common
    - default: runtimes
      template_variables:
        builder_level: episode
        vertical_align: top
        horizontal_align: left
    - default: ratings
      template_variables:
        builder_level: episode
        rating3: user
        rating3_image: imdb
        vertical_position: bottom
        horizontal_position: left
        rating3_font_size: 120
    - default: streaming
      template_variables:
        vertical_align: bottom
        horizontal_align: right
    - default: ratings
      template_variables:
        rating3: user
        rating3_image: imdb
        vertical_position: bottom
        horizontal_position: left
    operations:
      mass_user_rating_update: imdb
      mass_episode_user_rating_update: imdb
      split_duplicates: false
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:
plex:
  url: <<PLEX_URLL>>
  token: <<PLEX_TOKENN>>
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
  db_cache:
  verify_ssl:
tmdb:
  apikey: <<TMDB_API_KEY>>
  language: en
  cache_expiration: 60
  region:
mdblist:
  apikey: <<MDB_API_KEY>>
  cache_expiration: 60
```

### Logs

https://gist.github.com/rafapirotto/e2b37800001e370a7cf1423224e0416f

**Comment by antwanchild** [comment]
This is not a bug. This is a cache issue. Please try deleting the cache and rerunning

**Comment by YozoraXCII** [comment]
Your log is also saying you should update to 2.1.0

```
[2024-10-20 17:45:52,187] [kometa.py:273]             [INFO]     |     Version: 2.0.2 (Docker: master)                                                                |
[2024-10-20 17:45:52,356] [kometa.py:275]             [INFO]     |     Newest Version: 2.1.0    
```

**Comment by rafapirotto** [comment]
Doing the plex dance fixed the issue. I do however think that the cache issue is worth being investigated. It appears that I'm not the only one with this issue. @antwanchild said yesterday to me in discord that he has had this issue in the past before as well as I have had this issue a couple of times.

**Comment by antwanchild** [comment]
I had the issue, not related specifically to an episode, but an issue where renaming the cache fixed what i was having issue with

**Comment by rafapirotto** [comment]
> I had the issue, not related specifically to an episode, but an issue where renaming the cache fixed what i was having issue with

The problem with that fix is that renaming the cache forces a new cache to be built which takes way too much time. I don't consider that to be an optimal solution. I rather believe that investigation the cause of the cache issue is worth pursuing.

**Comment by antwanchild** [comment]
> The problem with that fix is that renaming the cache forces a new cache to be built which takes way too much time. I don't consider that to be an optimal solution. I rather believe that investigation the cause of the cache issue is worth pursuing.

This is the reason you were asked for logs of when it was added Kometa and when Kometa updated the rating and stated it applied an overlay when it actually didn't

**Comment by chazlarson** [comment]
When Kometa applies an overlay, it saves a record of all aspects of the overlay in the cache.

For example:
```
"1080Presolution100left1515top305105center(0, 0, 0, 153)3000"
```

On subsequent runs, if that record has not changed, Kometa figures that the current overlay matches the one it's about to apply, so "No Overlay Update Needed"

If you delete the cache, nothing matches so everything gets updated.
When you Plex dance, now the item no longer has an overlay, so it gets regenerated and updated.

For some reason, Kometa thought that the thing already had the overlays it was supposed to have.

Perhaps there was some inconsistency, perhaps the "what overlay did I apply" is incomplete [I think only position changes aren't captured for some overlays, for example].

**Comment by rafapirotto** [comment]
> When Kometa applies an overlay, it saves a record of all aspects of the overlay in the cache.
> 
> For example:
> 
> ```
> "1080Presolution100left1515top305105center(0, 0, 0, 153)3000"
> ```
> 
> On subsequent runs, if that record has not changed, Kometa figures that the current overlay matches the one it's about to apply, so "No Overlay Update Needed"
> 
> If you delete the cache, nothing matches so everything gets updated. When you Plex dance, now the item no longer has an overlay, so it gets regenerated and updated.
> 
> For some reason, Kometa thought that the thing already had the overlays it was supposed to have.
> 
> Perhaps there was some inconsistency, perhaps the "what overlay did I apply" is incomplete [I think only position changes aren't captured for some overlays, for example].

For more background, the episode was added to plex on october the 16th. The problematic episode was the 8th episode of the second season of Tell me Lies
I have found old logs in my backups which may help debug this @antwanchild :
![image](https://github.com/user-attachments/assets/040adb07-7aa5-492b-a743-22ed7830c90d)

[old logs.zip](https://github.com/user-attachments/files/17464240/old.logs.zip)

Hope this helps!

**Comment by rafapirotto** [comment]
I have more recent logs if those are neede

**Comment by chazlarson** [comment]
Seems like there's some logic error in there.  Once it gets an overlay future changes in the rating don't apply a new overlay.
```
episode arrives:
| Processing Tell Me Lies S02E08
| No imdb User Rating Found

| Tell Me Lies S02E08
|   Overlay Warning: No <<user_rating>> found
|   Overlays Applied: Overlay File (1) runtime_info, Overlay File (2) Rating3Fresh

11 hours later:
| Processing Tell Me Lies S02E08
| No imdb User Rating Found

| Tell Me Lies S02E08
|   Overlay Warning: No <<user_rating>> found
|   Overlays Applied: Overlay File (1) runtime_info, Overlay File (2) Rating3Fresh

three hours later:
| Processing Tell Me Lies S02E08
| No imdb User Rating Found

LOG ENDS PREMATURELY

9 hours later:
| Processing Tell Me Lies S02E08
| Item Edits:
| Update User Rating (Batched) | 8.8

| Tell Me Lies S02E08
|   Overlay Update Not Needed

12 hours later:
| Processing Tell Me Lies S02E08
| Item Edits:
| Update User Rating (Batched) | 8.8

| Tell Me Lies S02E08
|   Overlay Update Not Needed

12 hours later:
| Processing Tell Me Lies S02E08
| Item Edits:
| Update User Rating (Batched) | 8.9

| Tell Me Lies S02E08
|   Overlay Update Not Needed

12 hours later:
| Processing Tell Me Lies S02E08

| Tell Me Lies S02E08
|   Overlay Update Not Needed

12 hours later:
| Processing Tell Me Lies S02E08
| Item Edits:
| Update User Rating (Batched) | 9.1

| Tell Me Lies S02E08
|   Overlay Update Not Needed

```

**Comment by chazlarson** [comment]
What's in `overlays/common`?

**Comment by rafapirotto** [comment]
> What's in `overlays/common`?

```
overlays:
  4K:
    overlay:
      name: 4K
      file: overlays/common/4K.png
    plex_search:
      all:
        resolution: 4K
```

**Comment by rafapirotto** [comment]
> Seems like there's some logic error in there. Once it gets an overlay future changes in the rating don't apply a new overlay.

So you are confirming this is indeed a bug and that it can be fixed in a future release?

**Comment by chazlarson** [comment]
I'm just commenting on what I'm seeing in your logs.  That's data from your log files.  I haven't reproduced it, though those tests are ongoing.

**Comment by chazlarson** [comment]
It looks like there's an issue going to or from a null rating:
https://docs.google.com/document/d/1cexxP_tyINM3oy1yYVkn0hEAjN-Kt94aK78X-GC4YpM/edit?usp=sharing

**Comment by rafapirotto** [comment]
> It looks like there's an issue going to or from a null rating: https://docs.google.com/document/d/1cexxP_tyINM3oy1yYVkn0hEAjN-Kt94aK78X-GC4YpM/edit?usp=sharing

Interesting. So it is looking like an interesting bug. I'm happy to hear that, I thought I was crazy cause it was happening to me and not everyone else

**Comment by rafapirotto** [comment]
Is there anything else you need from my side? More logs or something? Also, which is the next step for this? Will this be treated as a bug? @chazlarson

**Comment by chazlarson** [comment]
Nothing else needed here.  Future action is dependent on the author reviewing it.

**Comment by rafapirotto** [comment]
> Nothing else needed here. Future action is dependent on the author reviewing it.

Should I tag him?

**Comment by chazlarson** [comment]
No need, this issue is assigned to him.

**Comment by YozoraXCII** [comment]
This is ready to be tested using the `overlay-episode-fix` branch. #2296

If testing works as expected we will push this into nightly.

**Comment by rafapirotto** [comment]
> This is ready to be tested using the `overlay-episode-fix` branch. #2296
> 
> If testing works as expected we will push this into nightly.

Excellent! Once I see it happening again, I will try it out! Big thank you!

**Comment by rafapirotto** [comment]
@YozoraXCII @chazlarson @antwanchild @meisnate12 I think may still be happening:
I'm using nightly (since this was [merged in #2296](https://github.com/Kometa-Team/Kometa/commits/nightly/)) and I still don't get the overlay for some tv shows:
https://www.imdb.com/title/tt33366664/episodes/?ref_=tt_eps_sm
![image](https://github.com/user-attachments/assets/0c09c657-7c9c-4791-8506-224b4503fb44)
![image](https://github.com/user-attachments/assets/652fd9e6-e6d0-47df-a94f-11e3b85d47ca)
https://www.imdb.com/title/tt15469618/episodes/?season=2
As you can see from imdb, these already have scores, however they don't appear to have an imdb score overlay
Here are the logs:
[meta.log](https://github.com/user-attachments/files/17805241/meta.log)

**Comment by YozoraXCII** [comment]
Neither `Cromañon` nor `Bad Sisters` appear in that log file

**Comment by chazlarson** [comment]
@rafapirotto That log contains no references to a show called "Bad Sisters".

**Comment by rafapirotto** [comment]
Let me correct that

**Comment by rafapirotto** [comment]
There you go @YozoraXCII @chazlarson

**Comment by rafapirotto** [comment]
Just to double check, were you able to see the updated link? If you need anything else like more logs just ask!
@YozoraXCII @chazlarson 
Thanks!

**Comment by YozoraXCII** [comment]
> Just to double check, were you able to see the updated link? If you need anything else like more logs just ask!
> @YozoraXCII @chazlarson 
> Thanks!

Got the link but I can't personally look until tomorrow

I tested earlier and confirmed the issue of null ratings appears to be fixed in nightly. Are you running the latest nightly build?

If yes, try deleting your config.cache and doing another run. If that doesn't work, maybe try removing your overlays and letting it start from scratch

**Comment by rafapirotto** [comment]
> > Just to double check, were you able to see the updated link? If you need anything else like more logs just ask!
> > @YozoraXCII @chazlarson
> > Thanks!
> 
> Got the link but I can't personally look until tomorrow
> 
> I tested earlier and confirmed the issue of null ratings appears to be fixed in nightly. Are you running the latest nightly build?
> 
> If yes, try deleting your config.cache and doing another run. If that doesn't work, maybe try removing your overlays and letting it start from scratch

Hey!

I am using the latest nightly build. I don't think delete the cache or removing the overlays is the solution. This shouldn't happen in the first place. This has been happening to me lately, before and after the fix. Also, I specifically ran another run and I had the results you are seeing. I am running docker with the latest nightly build

**Comment by chazlarson** [comment]
All the log shows is that Kometa thinks the ratings are up to date and Kometa sees no reason to update the overlays.

Perhaps running in trace mode would provide more specifics about why exactly Kometa doesn't think it has to update the ratings.

Perhaps hiding the cache would show if there's a cache issue that needs to be addressed.

Perhaps forcing a reapply of the overlays [or removing and reapplying] would clear whatever is telling Kometa that it doesn't need to.

These are tests you can run to try to reproduce a problem which we cannot, in an effort to try to determine the cause.

All we can see form that log is:
1. Kometa thinks the ratings are up to date
2. Kometa doesn't think the overlays have changed.

The log doesn't show *why* Kometa may think that; some of these other tests may.

**Comment by rafapirotto** [comment]
> All the log shows is that Kometa thinks the ratings are up to date and Kometa sees no reason to update the overlays.
> 
> Perhaps running in trace mode would provide more specifics about why exactly Kometa doesn't think it has to update the ratings.
> 
> Perhaps hiding the cache would show if there's a cache issue that needs to be addressed.
> 
> Perhaps forcing a reapply of the overlays [or removing and reapplying] would clear whatever is telling Kometa that it doesn't need to.
> 
> These are tests you can run to try to reproduce a problem which we cannot, in an effort to try to determine the cause.
> 
> All we can see form that log is:
> 
> 1. Kometa thinks the ratings are up to date
> 2. Kometa doesn't think the overlays have changed.
> 
> The log doesn't show _why_ Kometa may think that; some of these other tests may.

Hey! Thanks for the reply.

As I said before, I have tried both hiding/deleting the cache and force the overlays in the past and both solve my problem. The thing is that I need to be manually checking each time to see if overlays are missing and then manually either delete the cache and wait for that run to run (which in my experience takes longer than a normal run because of course it does not have any cached stuff). Or, manually run a reapply overlay. My gut tells me it is something either cache related or related to the logic behind how kometa decides if something needs an update. I have yet to find the exact way to recreate this issue. What I know is that is happens with episodes that have aired recently. Like I download an episode and it doesn’t yet have a rating in imdb, and it gets stuck like that even after imdb gets a rating. I can run trace mode and provide the logs, but if I reapply overlays or delete/hide the cache I will solve my problem but I will also reset the current conditions that depict my problem and I would have to wait for another episode or tv show to air and also the imdb rating would have to be missing. This all is a bit time consuming 😓

**Comment by chazlarson** [comment]
The recent-episode situation is exactly what led to this initially and is the situation which is believed to have been fixed.

Coming up with a repeatable recipe is a requirement for fixing whatever may still remain.

**Comment by chazlarson** [comment]
Perhaps uploading your cache file would be a thing that would be useful.

**Comment by rafapirotto** [comment]
> The recent-episode situation is exactly what led to this initially and is the situation which is believed to have been fixed.
> 
> Coming up with a repeatable recipe is a requirement for fixing whatever may still remain.

I know that was the case, but the fact that I am running the nightly build and this still happens show that there is still something wrong.

**Comment by rafapirotto** [comment]
> Perhaps uploading your cache file would be a thing that would be useful.

Sure! I will get that tomorrow!

**Comment by rafapirotto** [comment]
@chazlarson here is my cache
[config.cache.zip](https://github.com/user-attachments/files/17815973/config.cache.zip)

**Comment by rafapirotto** [comment]
I'm also running with trace mode, will provide the logs soon

**Comment by rafapirotto** [comment]
Here is the logs with trace enabled:

[meta.log](https://github.com/user-attachments/files/17817022/meta.log)

CC: @chazlarson

**Comment by chazlarson** [comment]
There's something to patch in here yet.

I created a library containing only Bad Sisters with all 8 episodes in season 2, so of course most don't have IMDB ratings.

Overlays appeared as expected, then I gave episode three a user rating, disabled the rating-setting operations, and ran Kometa again.  No overlay appeared on that episode since Kometa thought it didn't need to be updated.

**Comment by rafapirotto** [comment]
> There's something to patch in here yet.
> 
> I created a library containing only Bad Sisters with all 8 episodes in season 2, so of course most don't have IMDB ratings.
> 
> Overlays appeared as expected, then I gave episode three a user rating, disabled the rating-setting operations, and ran Kometa again. No overlay appeared on that episode since Kometa though it didn't need to be updated.

So are you saying that there is still a bug that needs to be fixed? @chazlarson

**Comment by chazlarson** [comment]
Appears there may be.

**Comment by rafapirotto** [comment]
> Appears there may be.

Should I tag somebody? @chazlarson

**Comment by chazlarson** [comment]
the issue is already assigned to the author

**Comment by YozoraXCII** [comment]
> There's something to patch in here yet.
> 
> I created a library containing only Bad Sisters with all 8 episodes in season 2, so of course most don't have IMDB ratings.
> 
> Overlays appeared as expected, then I gave episode three a user rating, disabled the rating-setting operations, and ran Kometa again. No overlay appeared on that episode since Kometa thought it didn't need to be updated.

I can't seem to reproduce this, or am I missing something?

My cache is set to `true` for these tests.

Run 1 - I clean my library
```yaml
libraries:
  Kometa-One-Show:
    remove_overlays: true
    operations:
      mass_episode_user_rating_update: reset
```
![image](https://github.com/user-attachments/assets/0ce5b470-dd03-4c67-9e86-8aa3275aef35)

Run 2 - I do an initial run with `runtimes` and `ratings`
```yaml
libraries:
  Kometa-One-Show:
    overlay_files:
      - default: runtimes
        template_variables:
          builder_level: episode
          vertical_align: top
          horizontal_align: left
      - default: ratings
        template_variables:
          builder_level: episode
          rating1: user
          rating1_image: imdb
```
![image](https://github.com/user-attachments/assets/53b9c961-55d0-4e4b-8098-99525ff7c270)

![image](https://github.com/user-attachments/assets/bcd359d5-69af-4188-aecb-37be33cf26c7)

Run 3 - I set the episode user rating to IMDb and run overlays again:

```yaml
libraries:
  Kometa-One-Show:
    operations:
      mass_episode_user_rating_update: imdb
    overlay_files:
      - default: runtimes
        template_variables:
          builder_level: episode
          vertical_align: top
          horizontal_align: left
      - default: ratings
        template_variables:
          builder_level: episode
          rating1: user
          rating1_image: imdb
```
![image](https://github.com/user-attachments/assets/fabb26bb-6017-4285-b4d9-8ebed6bbba2d)

![image](https://github.com/user-attachments/assets/09ccf49f-a1f8-44ce-9223-d63bc5487ddd)

**Comment by chazlarson** [comment]
The issue is when an episode that doesn't have an IMDB rating yet gets an overlay.  When it gets a rating, the overlay is not updated with the now-existing rating.

**Comment by YozoraXCII** [comment]
> The issue is when an episode that doesn't have an IMDB rating yet gets an overlay. When it gets a rating, the overlay is not updated with the now-existing rating.

Understood - the next episode of Bad Sisters airs today (Nov 20th) so if the dataset is updated in time tomorrow I should hopefully be able to reproduce this

**Comment by chazlarson** [comment]
## EDIT
This run was using master; when I do the same thing with nightly I cannot reproduce the issue
## EDIT

Created a new library containing only Bad Sisters, placeholders for all episodes.

No IMDB ratings exist for anything past S02 E03.

Running this:

```yaml
libraries:
  Just Bad Sisters:
    overlay_files:
    - default: runtimes
      template_variables:
        builder_level: episode
        vertical_align: top
        horizontal_align: left
    - default: ratings
      template_variables:
        builder_level: episode
        rating3: user
        rating3_image: imdb
        vertical_position: bottom
        horizontal_position: left
        rating3_font_size: 120
    - default: ratings
      template_variables:
        rating3: user
        rating3_image: imdb
        vertical_position: bottom
        horizontal_position: left
    operations:
      mass_user_rating_update: imdb
      mass_episode_user_rating_update: imdb
      split_duplicates: false
```

Gives me this:

![image](https://github.com/user-attachments/assets/d6b630bc-2a3e-42c5-881b-31f5925d2e2f)

No rating, no overlay on episode 4:

![image](https://github.com/user-attachments/assets/f00aaab0-b547-44b4-b082-876f7a015f13)

Give it a user rating:

![image](https://github.com/user-attachments/assets/d8b43768-6047-44e9-b683-c9028dd4e226)

Disable the ratings operations so that rating doesn't get stomped:

```yaml
libraries:
  Just Bad Sisters:
    overlay_files:
    - default: runtimes
      template_variables:
        builder_level: episode
        vertical_align: top
        horizontal_align: left
    - default: ratings
      template_variables:
        builder_level: episode
        rating3: user
        rating3_image: imdb
        vertical_position: bottom
        horizontal_position: left
        rating3_font_size: 120
    - default: ratings
      template_variables:
        rating3: user
        rating3_image: imdb
        vertical_position: bottom
        horizontal_position: left
#     operations:
#       mass_user_rating_update: imdb
#       mass_episode_user_rating_update: imdb
#       split_duplicates: false
```

Rerun Kometa:

```
| Bad Sisters S02E04                                                                                 |
|   Overlay Update Not Needed                                                                        |
```

User rating still there:

![image](https://github.com/user-attachments/assets/d79516fd-e3e9-4f82-941d-763f42f0da92)

**Comment by YozoraXCII** [comment]
> Created a new library containing only Bad Sisters, placeholders for all episodes.
> 
> No IMDB ratings exist for anything past S02 E03.
> 
> Running this:
> 
> ```yaml
> libraries:
>   Just Bad Sisters:
>     overlay_files:
>     - default: runtimes
>       template_variables:
>         builder_level: episode
>         vertical_align: top
>         horizontal_align: left
>     - default: ratings
>       template_variables:
>         builder_level: episode
>         rating3: user
>         rating3_image: imdb
>         vertical_position: bottom
>         horizontal_position: left
>         rating3_font_size: 120
>     - default: ratings
>       template_variables:
>         rating3: user
>         rating3_image: imdb
>         vertical_position: bottom
>         horizontal_position: left
>     operations:
>       mass_user_rating_update: imdb
>       mass_episode_user_rating_update: imdb
>       split_duplicates: false
> ```
> 
> Gives me this:
> 
> ![image](https://private-user-images.githubusercontent.com/3865541/388159074-d6b630bc-2a3e-42c5-881b-31f5925d2e2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTg3NzksIm5iZiI6MTczMjExODQ3OSwicGF0aCI6Ii8zODY1NTQxLzM4ODE1OTA3NC1kNmI2MzBiYy0yYTNlLTQyYzUtODgxYi0zMWY1OTI1ZDJlMmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTYwMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTgxMWU2MmUwNjVhYTk3OTkyZDRlNjAxYWJjMDJjNjQ4MjczMDIwNzhkNjYwODJhYmM4MGIyZThmMzNhYjA2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5Ctd8whcc8KV67_FcN7urGIQZVQJJaXsoyLzO7UgL64)
> 
> No rating, no overlay on episode 4:
> 
> ![image](https://private-user-images.githubusercontent.com/3865541/388159924-f00aaab0-b547-44b4-b082-876f7a015f13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTg3NzksIm5iZiI6MTczMjExODQ3OSwicGF0aCI6Ii8zODY1NTQxLzM4ODE1OTkyNC1mMDBhYWFiMC1iNTQ3LTQ0YjQtYjA4Mi04NzZmN2EwMTVmMTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTYwMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzUwNjEzMDlkODk0NjE5NWRlNmE3YWViOTI3NzNkMTA1ZDYyOGFkYmI4NWRhMGJhMTEyYmNmNzkwZjFjYTAyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.MDMsZ5NqDlQZCQPeMUhlU5oRZAAsJ-QKbmxzIUb5N6M)
> 
> Give it a user rating:
> 
> ![image](https://private-user-images.githubusercontent.com/3865541/388160132-d8b43768-6047-44e9-b683-c9028dd4e226.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTg3NzksIm5iZiI6MTczMjExODQ3OSwicGF0aCI6Ii8zODY1NTQxLzM4ODE2MDEzMi1kOGI0Mzc2OC02MDQ3LTQ0ZTktYjY4My1jOTAyOGRkNGUyMjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTYwMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWJjZjQzNDI1OWUyOTJkZWVkMGE3MDc3ODAzNmZjNTE5MDBkOWJiMTU1NDZiODRjYmFhNmZjMTA0NmNmYTE2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.DhaC6uUvxYoNv8OOq18W0Y_2nDsr98dZl2Yky_OELII)
> 
> Disable the ratings operations so that rating doesn't get stomped:
> 
> ```yaml
> libraries:
>   Just Bad Sisters:
>     overlay_files:
>     - default: runtimes
>       template_variables:
>         builder_level: episode
>         vertical_align: top
>         horizontal_align: left
>     - default: ratings
>       template_variables:
>         builder_level: episode
>         rating3: user
>         rating3_image: imdb
>         vertical_position: bottom
>         horizontal_position: left
>         rating3_font_size: 120
>     - default: ratings
>       template_variables:
>         rating3: user
>         rating3_image: imdb
>         vertical_position: bottom
>         horizontal_position: left
> #     operations:
> #       mass_user_rating_update: imdb
> #       mass_episode_user_rating_update: imdb
> #       split_duplicates: false
> ```
> 
> Rerun Kometa:
> 
> ```
> | Bad Sisters S02E04                                                                                 |
> |   Overlay Update Not Needed                                                                        |
> ```
> 
> User rating still there:
> 
> ![image](https://private-user-images.githubusercontent.com/3865541/388161120-d79516fd-e3e9-4f82-941d-763f42f0da92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTg3NzksIm5iZiI6MTczMjExODQ3OSwicGF0aCI6Ii8zODY1NTQxLzM4ODE2MTEyMC1kNzk1MTZmZC1lM2U5LTRmODItOTQxZC03NjNmNDJmMGRhOTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTYwMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGNkNTllNzUxY2UzNmY0OGIzNDFjNTljMmMxNWU0OTZiZGMxZjdkZTQ3ODNmNzM0NjJiZjdmZWQ4YjNhZmM0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8oTXpDg12Wsj3gpWrLRKbaHIl-QjHdSXw6nsG_Cfw4I)

I can't reproduce this either.

New Library named the same as yours

![image](https://github.com/user-attachments/assets/83481196-41cf-47d2-ad07-faa7cfd4d0e3)


Run 1 - copied and pasted your YAML:

```yaml
libraries:
  Just Bad Sisters:
    overlay_files:
    - default: runtimes
      template_variables:
        builder_level: episode
        vertical_align: top
        horizontal_align: left
    - default: ratings
      template_variables:
        builder_level: episode
        rating3: user
        rating3_image: imdb
        vertical_position: bottom
        horizontal_position: left
        rating3_font_size: 120
    - default: ratings
      template_variables:
        rating3: user
        rating3_image: imdb
        vertical_position: bottom
        horizontal_position: left
    operations:
      mass_user_rating_update: imdb
      mass_episode_user_rating_update: imdb
      split_duplicates: false
```

![image](https://github.com/user-attachments/assets/a6927f52-fc52-40ac-a830-8e0b87dbd21b)

Episode 4 has a rating because it carries over from the previous rating I gave the show against the previous library, so I'll use S02E05 as my example which has no rating and no overlay:

![image](https://github.com/user-attachments/assets/8805882b-5daf-4a13-af58-ad61d9769f0a)

Give it a user rating:

![image](https://github.com/user-attachments/assets/0a5acb2b-0cb2-48e8-9c10-23468fb11f36)

Remove the operations to prevent stomp:

```yaml
libraries:
  Just Bad Sisters:
    overlay_files:
    - default: runtimes
      template_variables:
        builder_level: episode
        vertical_align: top
        horizontal_align: left
    - default: ratings
      template_variables:
        builder_level: episode
        rating3: user
        rating3_image: imdb
        vertical_position: bottom
        horizontal_position: left
        rating3_font_size: 120
    - default: ratings
      template_variables:
        rating3: user
        rating3_image: imdb
        vertical_position: bottom
        horizontal_position: left
    operations:
      split_duplicates: false
```

S02E05 now has a rating overlay

![image](https://github.com/user-attachments/assets/65bc244a-550c-4392-9c13-92188f7dbc06)

**Comment by YozoraXCII** [comment]
If it helps:

Version: 2.1.0-build20 (Python 3.12.3) (Git: nightly)
Platform: Windows-11-10.0.22631-SP0
Connected to server Kometa Test version 1.41.2.9200-c6bbc1b53
Agent: tv.plex.agents.series
Scanner: Plex TV Series

**Comment by chazlarson** [comment]
Weird:
```
|     Version: 2.1.0 (Python 3.12.6) (Git: master)                                                   |
|     Platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.35                                         |
...
| Connected to server chaz-plex version 1.40.0.7998-c29d4c0c8                                        |
| Running on Linux version 6.8.0-45-generic                                                          |
| Plex DB cache setting: 40 MB                                                                       |
| PlexPass: True on Public update channel.                                                           |
| Scheduled maintenance running between 2:00 and 5:00                                                |
| Connected to library Just Bad Sisters                                                              |
| Type: Show                                                                                         |
| Agent: tv.plex.agents.series                                                                       |
| Scanner: Plex TV Series                                                                            |
| Ratings Source: N/A                                                                                |
```
I wonder if that ratings source has something to do with it?

**Comment by chazlarson** [comment]
I thought I was on nightly.

Let me try again with nightly.

**Comment by chazlarson** [comment]
Cannot reproduce using nightly.

First run:
```
| Bad Sisters S02E04                                                                                 |
|   Overlays Applied: Overlay File (0) runtime_info, Overlay File (1) Rating3Fresh                   |
|                                                                                                    |
| Bad Sisters S02E05                                                                                 |
|   Overlays Applied: Overlay File (0) runtime_info                                                  |
|                                                                                                    |
| Bad Sisters S02E06                                                                                 |
|   Overlays Applied: Overlay File (0) runtime_info                                                  |
```
Then I give S02E05 a user rating and run again:
```
| Bad Sisters S02E04                                                                                 |
|   Overlay Update Not Needed (Current Overlays: Overlay File (0) runtime_info, Overlay File (1) Rating3Fresh) |
|                                                                                                    |
| Bad Sisters S02E05                                                                                 |
|   Overlays Applied: Overlay File (0) runtime_info, Overlay File (1) Rating3Fresh                   |
|                                                                                                    |
| Bad Sisters S02E06                                                                                 |
|   Overlay Update Not Needed (Current Overlays: Overlay File (0) runtime_info)                      |
```

![image](https://github.com/user-attachments/assets/1d164084-6141-4c10-bc4b-0e8499e65bbe)

Give S02E06 a rating and run Kometa:

```
| Bad Sisters S02E04                                                                                 |
|   Overlay Update Not Needed (Current Overlays: Overlay File (0) runtime_info, Overlay File (1) Rating3Fresh) |
|                                                                                                    |
| Bad Sisters S02E05                                                                                 |
|   Overlay Update Not Needed (Current Overlays: Overlay File (0) runtime_info, Overlay File (1) Rating3Fresh) |
|                                                                                                    |
| Bad Sisters S02E06                                                                                 |
|   Overlays Applied: Overlay File (0) runtime_info, Overlay File (1) Rating3Rotten                  |
```

![image](https://github.com/user-attachments/assets/3f819c1e-a4aa-4f89-98ca-6db9dd84dc2c)

**Comment by rafapirotto** [comment]
> Cannot reproduce using nightly.
> 
> First run:
> 
> ```
> | Bad Sisters S02E04                                                                                 |
> |   Overlays Applied: Overlay File (0) runtime_info, Overlay File (1) Rating3Fresh                   |
> |                                                                                                    |
> | Bad Sisters S02E05                                                                                 |
> |   Overlays Applied: Overlay File (0) runtime_info                                                  |
> |                                                                                                    |
> | Bad Sisters S02E06                                                                                 |
> |   Overlays Applied: Overlay File (0) runtime_info                                                  |
> ```
> 
> Then I give S02E05 a user rating and run again:
> 
> ```
> | Bad Sisters S02E04                                                                                 |
> |   Overlay Update Not Needed (Current Overlays: Overlay File (0) runtime_info, Overlay File (1) Rating3Fresh) |
> |                                                                                                    |
> | Bad Sisters S02E05                                                                                 |
> |   Overlays Applied: Overlay File (0) runtime_info, Overlay File (1) Rating3Fresh                   |
> |                                                                                                    |
> | Bad Sisters S02E06                                                                                 |
> |   Overlay Update Not Needed (Current Overlays: Overlay File (0) runtime_info)                      |
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/3865541/388187162-1d164084-6141-4c10-bc4b-0e8499e65bbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjE1NDksIm5iZiI6MTczMjEyMTI0OSwicGF0aCI6Ii8zODY1NTQxLzM4ODE4NzE2Mi0xZDE2NDA4NC02MTQxLTRjMTAtYmM0Yi0wZTg0OTllNjViYmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTY0NzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQyZmRjZWUxNDFhNjVmNGY3NWJmNWJkZmQ0NWI5MmMyZWI1N2FmYWFiZmY2YjcwNTAxZDM4ZDZlMWM5ODU5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Xzkp-HnQRNfFqBbHBPEiX0JbWOkA016pvY4PdsMEwQ8)
> 
> Give S02E06 a rating and run Kometa:
> 
> ```
> | Bad Sisters S02E04                                                                                 |
> |   Overlay Update Not Needed (Current Overlays: Overlay File (0) runtime_info, Overlay File (1) Rating3Fresh) |
> |                                                                                                    |
> | Bad Sisters S02E05                                                                                 |
> |   Overlay Update Not Needed (Current Overlays: Overlay File (0) runtime_info, Overlay File (1) Rating3Fresh) |
> |                                                                                                    |
> | Bad Sisters S02E06                                                                                 |
> |   Overlays Applied: Overlay File (0) runtime_info, Overlay File (1) Rating3Rotten                  |
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/3865541/388187684-3f819c1e-a4aa-4f89-98ca-6db9dd84dc2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjE1NDksIm5iZiI6MTczMjEyMTI0OSwicGF0aCI6Ii8zODY1NTQxLzM4ODE4NzY4NC0zZjgxOWMxZS1hNGFhLTRmODktOThjYS02ZGI5ZGQ4NGRjMmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTY0NzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU2MDYxMjUzM2M3YmE0ZGM3YTU4Yzk1Njc0YzU5ZDQyNDdmZjk3YjIwMmYzM2NlNjIxNmE5ZTE1MjljNGFkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.uZLSM6R0FYfb5H7xvi1Vft9tfbaYshCGaI0EKQyPzbk)

And how can you explain what happens to me?

**Comment by rafapirotto** [comment]
None of my episodes have a rating overlay, not even now that multiple runs ocurred:
![image](https://github.com/user-attachments/assets/4bc21196-ddb7-4564-801a-ba5db16834a1)

**Comment by chazlarson** [comment]
> And how can you explain what happens to me?

I am not denying that you are seeing what you are seeing, just reporting that it cannot be generally reproduced so there is something peculiar to your situation that is triggering this.

I personally cannot explain what you're seeing.  Hopefully the data provided gives the author the means to determine what's going on.

**Comment by rafapirotto** [comment]
Maybe something in my config? Or maybe the nightly build on the docker image was not pushed yet?

**Comment by chazlarson** [comment]
I'll give it a shot with the docker image just to confirm or deny.

**Comment by rafapirotto** [comment]
Thanks a lot!

**Comment by YozoraXCII** [comment]
> None of my episodes have a rating overlay, not even now that multiple runs ocurred: ![image](https://private-user-images.githubusercontent.com/33788807/388189520-4bc21196-ddb7-4564-801a-ba5db16834a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjE3NzIsIm5iZiI6MTczMjEyMTQ3MiwicGF0aCI6Ii8zMzc4ODgwNy8zODgxODk1MjAtNGJjMjExOTYtZGRiNy00NTY0LTgwMWEtYmE1ZGIxNjgzNGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDE2NTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NjQzMTQ0MmI2NTAwNTlhYTUzMTQ4YWIyYjkwZjM3NWZlZGQwY2I2NjVjZGQzYTU1M2JiYmY2NDFlOWMyZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r8plB_HrlhQNoyxRRwQNOdx17YQPD8rZQicrKMQza7c)

Can you get me the XML data from S02E01 of Bad Sisters from a desktop device?

Hover over the episode > Three Dots icon > Get Info > View XML

**Comment by chazlarson** [comment]
current nightly docker is behaving in the same way for me.  add a rating, run Kometa, get overlay.

![image](https://github.com/user-attachments/assets/6e68378a-25b8-4339-a283-ec9e5de50db3)

So for better or worse it does not appear to be related to docker vs not

**Comment by rafapirotto** [comment]
> > None of my episodes have a rating overlay, not even now that multiple runs ocurred: ![image](https://private-user-images.githubusercontent.com/33788807/388189520-4bc21196-ddb7-4564-801a-ba5db16834a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMjE3NzIsIm5iZiI6MTczMjEyMTQ3MiwicGF0aCI6Ii8zMzc4ODgwNy8zODgxODk1MjAtNGJjMjExOTYtZGRiNy00NTY0LTgwMWEtYmE1ZGIxNjgzNGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDE2NTExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1NjQzMTQ0MmI2NTAwNTlhYTUzMTQ4YWIyYjkwZjM3NWZlZGQwY2I2NjVjZGQzYTU1M2JiYmY2NDFlOWMyZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r8plB_HrlhQNoyxRRwQNOdx17YQPD8rZQicrKMQza7c)
> 
> Can you get me the XML data from S02E01 of Bad Sisters from a desktop device?
> 
> Hover over the episode > Three Dots icon > Get Info > View XML

Here you go:
https://pastebin.com/q4nw2iKP

**Comment by YozoraXCII** [comment]
I'm not sure what to suggest other than removing your config.cache, if that doesn't work then do a `remove_overlays`

**Comment by rafapirotto** [comment]
> I'm not sure what to suggest other than removing your config.cache, if that doesn't work then do a `remove_overlays`

That will probably solve my problem but this will happen again. I just pulled the latest nightly build and I'm gonna run kometa again and share the logs and config.cache and any other thing that you guys think that it may help. I will also try to come up with better steps to recreate this, but this is still an issue.

**Comment by YozoraXCII** [comment]
> > I'm not sure what to suggest other than removing your config.cache, if that doesn't work then do a `remove_overlays`
> 
> That will probably solve my problem but this will happen again. I just pulled the latest nightly build and I'm gonna run kometa again and share the logs and config.cache and any other thing that you guys think that it may help. I will also try to come up with better steps to recreate this, but this is still an issue.

I think the issue exists in your cache file and we have since patched it which stops the issue from happening again, but won't resolve your cache.

When I look at your cache file, it says it has already applied the rating overlays, so it won't ever do them again unless the rating changes - removing the cache file or doing a remove_overlays gets aroudn this.

**Comment by rafapirotto** [comment]
> > > I'm not sure what to suggest other than removing your config.cache, if that doesn't work then do a `remove_overlays`
> > 
> > 
> > That will probably solve my problem but this will happen again. I just pulled the latest nightly build and I'm gonna run kometa again and share the logs and config.cache and any other thing that you guys think that it may help. I will also try to come up with better steps to recreate this, but this is still an issue.
> 
> I think the issue exists in your cache file and we have since patched it which stops the issue from happening again, but won't resolve your cache.
> 
> When I look at your cache file, it says it has already applied the rating overlays, so it won't ever do them again unless the rating changes - removing the cache file or doing a remove_overlays gets aroudn this.

You are saying that it won't do the rating overlays again unless the rating changes. The ratings change, specially for recently released content. I'm positive that the ratings have changed, and even in that case, I don't have a single rating overlay for any episode:
![image](https://github.com/user-attachments/assets/a2a72fb3-8ffb-497a-a4bc-57fa6b3fd175)

On another topic, I do have something I want to get straight. Are you saying that it is just a cache issue and that after deleting the cache it won't happen again? Like is it expected that my cache is out of date with the patch and that recreating it will cause to create a cache that will not have any issues in the future?

**Comment by YozoraXCII** [comment]
> > > > I'm not sure what to suggest other than removing your config.cache, if that doesn't work then do a `remove_overlays`
> > > 
> > > 
> > > That will probably solve my problem but this will happen again. I just pulled the latest nightly build and I'm gonna run kometa again and share the logs and config.cache and any other thing that you guys think that it may help. I will also try to come up with better steps to recreate this, but this is still an issue.
> > 
> > 
> > I think the issue exists in your cache file and we have since patched it which stops the issue from happening again, but won't resolve your cache.
> > When I look at your cache file, it says it has already applied the rating overlays, so it won't ever do them again unless the rating changes - removing the cache file or doing a remove_overlays gets aroudn this.
> 
> You are saying that it won't do the rating overlays again unless the rating changes. The ratings change, specially for recently released content. I'm positive that the ratings have changed, and even in that case, I don't have a single rating overlay for any episode: ![image](https://private-user-images.githubusercontent.com/33788807/388230140-a2a72fb3-8ffb-497a-a4bc-57fa6b3fd175.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMzAxMTQsIm5iZiI6MTczMjEyOTgxNCwicGF0aCI6Ii8zMzc4ODgwNy8zODgyMzAxNDAtYTJhNzJmYjMtOGZmYi00OTdhLWE0YmMtNTdmYTZiM2ZkMTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDE5MTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MTNjMjgzZjNhNzZiMjg2NzkxNmM3YTNhMDIwNjc0YTUwNzAyZjQ5MGRmZDk1YWFhYjcxOGI1NmY4NDA4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hs01fwR1csxFOrkAZlURO2n4hbLOfqSOcUDrPcc19FU)
> 
> On another topic, I do have something I want to get straight. Are you saying that it is just a cache issue and that after deleting the cache it won't happen again? Like is it expected that my cache is out of date with the patch and that recreating it will cause to create a cache that will not have any issues in the future?

All I can do is try to offer solutions - I appreciate how helpful you've been in assisting with providing all the info we've asked for, we're now at a stage where we cannot reproduce the issue on nightly when using "new" environments, so it appears to be an issue that exists within your cache/environment.

The cache file is the source of truth for Kometa to know what Overlays it has previously applied, and I can see for one of the episodes of Bad Sisters your cache says that it has already applied a ratings overlay (which I believe happened because of the bug that we have since fixed). We now need to tell Kometa "try again please", there is no way to tell it "you didn't actually apply that Overlay", so you either:
- Delete the cache file
- Do a `remove_overlays`
- Do a `reapply_overlays`

The cache will check what it currently holds as the rating against what exists in plex, and will then update the overlay if necessary. You could try manually adjusting one of the ratings to see if that has any positive impact, but if it doesn't then I suspect something has gone funky in the cache.

Regarding the latter comment - I can't guarantee that an issue will never be seen again, all I can say is that the initial issue you saw is no longer recreatable on a fresh environment with a fresh cache file. This has been proven by both chazlarson and I.

**Comment by rafapirotto** [comment]
> > > > > I'm not sure what to suggest other than removing your config.cache, if that doesn't work then do a `remove_overlays`
> > > > 
> > > > 
> > > > That will probably solve my problem but this will happen again. I just pulled the latest nightly build and I'm gonna run kometa again and share the logs and config.cache and any other thing that you guys think that it may help. I will also try to come up with better steps to recreate this, but this is still an issue.
> > > 
> > > 
> > > I think the issue exists in your cache file and we have since patched it which stops the issue from happening again, but won't resolve your cache.
> > > When I look at your cache file, it says it has already applied the rating overlays, so it won't ever do them again unless the rating changes - removing the cache file or doing a remove_overlays gets aroudn this.
> > 
> > 
> > You are saying that it won't do the rating overlays again unless the rating changes. The ratings change, specially for recently released content. I'm positive that the ratings have changed, and even in that case, I don't have a single rating overlay for any episode: ![image](https://private-user-images.githubusercontent.com/33788807/388230140-a2a72fb3-8ffb-497a-a4bc-57fa6b3fd175.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMzAxMTQsIm5iZiI6MTczMjEyOTgxNCwicGF0aCI6Ii8zMzc4ODgwNy8zODgyMzAxNDAtYTJhNzJmYjMtOGZmYi00OTdhLWE0YmMtNTdmYTZiM2ZkMTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDE5MTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MTNjMjgzZjNhNzZiMjg2NzkxNmM3YTNhMDIwNjc0YTUwNzAyZjQ5MGRmZDk1YWFhYjcxOGI1NmY4NDA4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hs01fwR1csxFOrkAZlURO2n4hbLOfqSOcUDrPcc19FU)
> > On another topic, I do have something I want to get straight. Are you saying that it is just a cache issue and that after deleting the cache it won't happen again? Like is it expected that my cache is out of date with the patch and that recreating it will cause to create a cache that will not have any issues in the future?
> 
> All I can do is try to offer solutions - I appreciate how helpful you've been in assisting with providing all the info we've asked for, we're now at a stage where we cannot reproduce the issue on nightly when using "new" environments, so it appears to be an issue that exists within your cache/environment.
> 
> The cache file is the source of truth for Kometa to know what Overlays it has previously applied, and I can see for one of the episodes of Bad Sisters your cache says that it has already applied a ratings overlay (which I believe happened because of the bug that we have since fixed). We now need to tell Kometa "try again please", there is no way to tell it "you didn't actually apply that Overlay", so you either:
> 
> * Delete the cache file
> * Do a `remove_overlays`
> * Do a `reapply_overlays`
> 
> The cache will check what it currently holds as the rating against what exists in plex, and will then update the overlay if necessary. You could try manually adjusting one of the ratings to see if that has any positive impact, but if it doesn't then I suspect something has gone funky in the cache.
> 
> Regarding the latter comment - I can't guarantee that an issue will never be seen again, all I can say is that the initial issue you saw is no longer recreatable on a fresh environment with a fresh cache file. This has been proven by both chazlarson and I.

I have some more information:
First of all, imdb has scores for episodes one through three of the second season of bad sisters:
<img width="917" alt="image" src="https://github.com/user-attachments/assets/d367bc78-16a0-4225-9c9a-25f3a44130b4">

So, I then renamed my cache and ran kometa using the nightly build and these are the results:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/857ad0b0-a72c-4904-8fd9-9d7e42ee5f97">

As you can see, I didn't get an overlay for episode three

Here are the logs with trace enabled:

[meta.log](https://github.com/user-attachments/files/17838816/meta.log)

And here is the old cache:
[old-config.cache.zip](https://github.com/user-attachments/files/17838824/old-config.cache.zip)

And the latest one:
[config.cache.zip](https://github.com/user-attachments/files/17838825/config.cache.zip)

Is this helpful? @chazlarson @YozoraXCII

**Comment by YozoraXCII** [comment]
> > > > > > I'm not sure what to suggest other than removing your config.cache, if that doesn't work then do a `remove_overlays`
> > > > > 
> > > > > 
> > > > > That will probably solve my problem but this will happen again. I just pulled the latest nightly build and I'm gonna run kometa again and share the logs and config.cache and any other thing that you guys think that it may help. I will also try to come up with better steps to recreate this, but this is still an issue.
> > > > 
> > > > 
> > > > I think the issue exists in your cache file and we have since patched it which stops the issue from happening again, but won't resolve your cache.
> > > > When I look at your cache file, it says it has already applied the rating overlays, so it won't ever do them again unless the rating changes - removing the cache file or doing a remove_overlays gets aroudn this.
> > > 
> > > 
> > > You are saying that it won't do the rating overlays again unless the rating changes. The ratings change, specially for recently released content. I'm positive that the ratings have changed, and even in that case, I don't have a single rating overlay for any episode: ![image](https://private-user-images.githubusercontent.com/33788807/388230140-a2a72fb3-8ffb-497a-a4bc-57fa6b3fd175.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMzAxMTQsIm5iZiI6MTczMjEyOTgxNCwicGF0aCI6Ii8zMzc4ODgwNy8zODgyMzAxNDAtYTJhNzJmYjMtOGZmYi00OTdhLWE0YmMtNTdmYTZiM2ZkMTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDE5MTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MTNjMjgzZjNhNzZiMjg2NzkxNmM3YTNhMDIwNjc0YTUwNzAyZjQ5MGRmZDk1YWFhYjcxOGI1NmY4NDA4ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hs01fwR1csxFOrkAZlURO2n4hbLOfqSOcUDrPcc19FU)
> > > On another topic, I do have something I want to get straight. Are you saying that it is just a cache issue and that after deleting the cache it won't happen again? Like is it expected that my cache is out of date with the patch and that recreating it will cause to create a cache that will not have any issues in the future?
> > 
> > All I can do is try to offer solutions - I appreciate how helpful you've been in assisting with providing all the info we've asked for, we're now at a stage where we cannot reproduce the issue on nightly when using "new" environments, so it appears to be an issue that exists within your cache/environment.
> > 
> > The cache file is the source of truth for Kometa to know what Overlays it has previously applied, and I can see for one of the episodes of Bad Sisters your cache says that it has already applied a ratings overlay (which I believe happened because of the bug that we have since fixed). We now need to tell Kometa "try again please", there is no way to tell it "you didn't actually apply that Overlay", so you either:
> > 
> > * Delete the cache file
> > * Do a `remove_overlays`
> > * Do a `reapply_overlays`
> > 
> > The cache will check what it currently holds as the rating against what exists in plex, and will then update the overlay if necessary. You could try manually adjusting one of the ratings to see if that has any positive impact, but if it doesn't then I suspect something has gone funky in the cache.
> > 
> > Regarding the latter comment - I can't guarantee that an issue will never be seen again, all I can say is that the initial issue you saw is no longer recreatable on a fresh environment with a fresh cache file. This has been proven by both chazlarson and I.
> 
> I have some more information:
> First of all, imdb has scores for episodes one through three of the second season of bad sisters:
> <img width="917" alt="image" src="https://github.com/user-attachments/assets/d367bc78-16a0-4225-9c9a-25f3a44130b4">
> 
> So, I then renamed my cache and ran kometa using the nightly build and these are the results:
> <img width="959" alt="image" src="https://github.com/user-attachments/assets/857ad0b0-a72c-4904-8fd9-9d7e42ee5f97">
> 
> As you can see, I didn't get an overlay for episode three
> 
> Here are the logs with trace enabled:
> 
> [meta.log](https://github.com/user-attachments/files/17838816/meta.log)
> 
> And here is the old cache:
> [old-config.cache.zip](https://github.com/user-attachments/files/17838824/old-config.cache.zip)
> 
> And the latest one:
> [config.cache.zip](https://github.com/user-attachments/files/17838825/config.cache.zip)
> 
> Is this helpful? @chazlarson @YozoraXCII 
> 
> 

When I checked earlier S02E03 did not have a rating.  The dataset for ratings that we use is only updated by IMDb once per day so I'm guessing that hasn't happened yet.

**Comment by chazlarson** [comment]
> As you can see, I didn't get an overlay for episode three

What if you give that episode a user rating and then run Kometa again?

**Comment by rafapirotto** [comment]
Well, @chazlarson @YozoraXCII , it appears it is working now. I will let you know if anything goes wrong again, thanks!

**Comment by YozoraXCII** [comment]
Closing for now, can be reopened in future if necessary
