### ISSUE TITLE
Not adding to Radarr

### ISSUE THREAD

**Issue by azra3l2805** [Kometa-Team/Kometa#312]
Hi,

Am trying out the script and the script says added to Radarr but there is nothing showing up on Radarr..

**Comment by meisnate12** [comment]
Can you post your meta.log

**Comment by azra3l2805** [comment]
am sorry. I dont know how to get that. Are you talking about the default radarr logs? I have it set to debug.

**Comment by meisnate12** [comment]
In your config folder for PMM (where your config.yml most likely is) you should have a folder called logs inside that folder should be a file called meta.log

**Comment by azra3l2805** [comment]
Attached. 
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/6749189/meta.log)

**Comment by azra3l2805** [comment]
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/6749197/meta.log)
Attached the correct log file

**Comment by meisnate12** [comment]
what version of radarr are you running

**Comment by azra3l2805** [comment]
![image](https://user-images.githubusercontent.com/83767172/124152319-0a314600-dab1-11eb-92cf-ee8599cfaca0.png)

3.2

**Comment by meisnate12** [comment]
nothing obvious is standing out to me ill have to run some more complicated tests later when I have time ill get back to you

**Comment by azra3l2805** [comment]
Thank you!

**Comment by meisnate12** [comment]
can you try using the develop branch and see if it works there? and if not send me the meta.log of that run

**Comment by azra3l2805** [comment]
radarrs Develop Branch? or PMM Develop Branch?

**Comment by meisnate12** [comment]
PMM

**Comment by azra3l2805** [comment]
I ran for 1 collection and it says being added to Radarr but its not.

**Comment by meisnate12** [comment]
can i get your log. btw this is all working for me so it might not be a code issue make sure your config is connecting properly

**Comment by azra3l2805** [comment]
This is my config for radarr.

radarr:                                
  url: http://radarr.xxxx.in
  token: ------
  version: v3
  add: true
  root_folder_path: "/mnt/radarr/Movies - English/"
  monitor: true
  availability: announced
  quality_profile: HD-1080p
  tag: collector
  search: false

**Comment by meisnate12** [comment]
And your log from the develop run?

**Comment by azra3l2805** [comment]
[meta2.log](https://github.com/meisnate12/Plex-Meta-Manager/files/6754617/meta2.log)

This is the log file

**Comment by meisnate12** [comment]
do you use docker or do you just run the script using python on your computer? From your log it appears to have partially updated the code but not all the way for some strange reason. i can tell you using dev because i fixed a small error when loading blank metadata files but on your radarr part i have this 
```
[2021-07-02 07:49:07,007] [radarr.py:71]              [INFO]     |                                                                                                    |
[2021-07-02 07:49:07,007] [radarr.py:72]              [DEBUG]    | TMDb IDs: [508943, 459151, 385128, 739542, 497698, 637693]                                         |
[2021-07-02 07:49:08,442] [radarr.py:112]             [INFO]     | Added to Radarr | 508943 | Luca                                                                    |
[2021-07-02 07:49:09,393] [radarr.py:112]             [INFO]     | Added to Radarr | 459151 | The Boss Baby: Family Business                                          |
[2021-07-02 07:49:10,334] [radarr.py:112]             [INFO]     | Added to Radarr | 385128 | F9                                                                      |
[2021-07-02 07:49:11,289] [radarr.py:112]             [INFO]     | Added to Radarr | 739542 | America: The Motion Picture                                             |
[2021-07-02 07:49:12,343] [radarr.py:112]             [INFO]     | Added to Radarr | 497698 | Black Widow                                                             |
[2021-07-02 07:49:13,295] [radarr.py:112]             [INFO]     | Added to Radarr | 637693 | Spirit Untamed                                                          |
[2021-07-02 07:49:13,296] [radarr.py:120]             [INFO]     | 6 Movies added to Radarr                                                                           |
```
notice how the beginning of the lines say radarr.py:112 (or other number). These are the line number in the code where these prints are and well ive updated the radarr.py in develop and it only has 61 lines total so something is wrong. Also if you are just using python on you computer make sure to install requirements again

**Comment by azra3l2805** [comment]
Am running the script on the computer. I tried removing everything and installing requirements and its still the same.

**Comment by meisnate12** [comment]
Go into your modules folder and open radarr.py how many lines does it have

**Comment by azra3l2805** [comment]
It has 132 lines of code

**Comment by azra3l2805** [comment]
[radarr.txt](https://github.com/meisnate12/Plex-Meta-Manager/files/6755007/radarr.txt)
This is my radarr.py

**Comment by meisnate12** [comment]
that file upload is not working for me i just get a blank page try using github gist or pastebin. if it has 132 then its wrong. This is the code for [radarr on the develop branch](https://github.com/meisnate12/Plex-Meta-Manager/blob/develop/modules/radarr.py)

**Comment by azra3l2805** [comment]
Can you like ping me the develop branch github cli link? Please?

**Comment by meisnate12** [comment]
`gh repo clone meisnate12/Plex-Meta-Manager`

**Comment by meisnate12** [comment]
theres no cli link for only devlop because its all the same repo just switch branches by doing `git checkout develop`

**Comment by azra3l2805** [comment]
yup, got it. Running the script now. Also ive added movies.yml, tvshows and anime.yml in the config folder to update collections. That should be fine right?

**Comment by meisnate12** [comment]
yea should be fine

**Comment by azra3l2805** [comment]
![image](https://user-images.githubusercontent.com/83767172/124295137-1e8b4680-db76-11eb-90c6-0c66f4e39d12.png)

Getting import error. 

ran pip3 install -r requirements.txt

**Comment by azra3l2805** [comment]
Okay, so the script is running but not adding anything to radarr.

![image](https://user-images.githubusercontent.com/83767172/124299064-9eb3ab00-db7a-11eb-8c8e-3cd1deefe67c.png)

**Comment by meisnate12** [comment]
Send me your meta.log

**Comment by azra3l2805** [comment]
[meta3.txt](https://github.com/meisnate12/Plex-Meta-Manager/files/6755743/meta3.txt)

This is the meta for the latest run

**Comment by azra3l2805** [comment]
![image](https://user-images.githubusercontent.com/83767172/124316202-d890ab80-db92-11eb-8dde-af231f20c10b.png)

This is new. Will attach log once it finishes running. Usually takes around 6-7 hrs for a full run.

**Comment by azra3l2805** [comment]
[meta4.txt](https://github.com/meisnate12/Plex-Meta-Manager/files/6756648/meta4.txt)

Updated Meta for the Item Not Found error. 

![image](https://user-images.githubusercontent.com/83767172/124321149-d3375f00-db9a-11eb-83c1-9350e04c2871.png)

**Comment by meisnate12** [comment]
can you try again with 1.11.0 make sure to update requirements if youre not using docker

**Comment by azra3l2805** [comment]
![image](https://user-images.githubusercontent.com/83767172/124715405-9a8fe080-df20-11eb-9125-24ba22454ce1.png)

Still the same error with 1.11.0

This is as per the meta.log 

![image](https://user-images.githubusercontent.com/83767172/124715883-1427ce80-df21-11eb-8601-c88e1f38dcf9.png)

I will attach the meta once its done running.

**Comment by azra3l2805** [comment]
Argghhhh am so dumb. 

I have Radarr running under https but was http on the url call. Thats why its failing.

Let me try running it with https.

**Comment by azra3l2805** [comment]
Its working perfectly now. 

Thank you so much!

Ill close this.
