### ISSUE TITLE
Feature Request: Don't write to main configuration file

### ISSUE THREAD

**Issue by aaronnuu** [Kometa-Team/Kometa#719]
Love the project, this is exactly what I was looking for to manage my collections, I just have one very minor gripe with it at the moment.

**Is your feature request related to a problem? Please describe.**
I am currently using Ansible to automate my media server deployments but every time I run my playbook the configuration file is either overwritten (even when I have made no changes to my static config), which means I have to re-authenticate with `trakt` the next time I run PMM, or I have to force it to only write when the file exists, which means any changes I make don't get propagated unless I delete the file manually.

**Describe the solution you'd like**
The problem is when authenticating with `trakt` the configuration file is modified. I would like the main configuration file to be completely static, and when authenticating with services maybe a new `authentications.yml` file could be created to store that information.

Thanks very much for the consideration and the great project

**Comment by meisnate12** [comment]
There's a --read-only mode but what version are you running because there was a bug with trakt auth in a previous version but it should be fixed with the latest

**Comment by aaronnuu** [comment]
Thanks for the quick response! I'm just running the latest docker container - looks like when running with the `-ro` flag I can't access my private `trakt` lists so it might still have the bug running in docker `meisnate12/plex-meta-manager:latest`.

With the read only config, would I have to re-authenticate every run? I am planning on using `trakt` as my source of truth for my lists, syncing them back with `radarr` and `sonarr` as well as adding a plex collection to keep things organised so I would like to be able to run the script using your container on a schedule.

For my use case the ideal situation is that the authentication details that would normally be written into the `config.yml` are just written somewhere else so they can still be accessed by the script in an automated way.

To be clear the manual step to take when I update my config with a new list takes a few seconds, so the effort to change this might be completely out of proportion with the problem it's causing me. My dream is just to have a 99.9% automated deployment for every service in my homelab so I thought I would ask.

**Comment by meisnate12** [comment]
You shouldn't have to use read only mode to not have the bug are you sure the base image has been updated what version number is at the beginning of you're meta.log file

**Comment by aaronnuu** [comment]
It's running on `Version: 1.15.1`

**Comment by meisnate12** [comment]
The trakt auth is supposed to save and just be accessed you should only have to authenticate once try switching to the develop branch and seeing if that works

**Comment by aaronnuu** [comment]
Develop branch `Version 1.15.1-develop69` throws errors when getting `trakt` lists, only when running with the `-ro` flag

```
|====================================================================================================|
|                                    Running marvel Metadata File                                    |
|                                         config/marvel.yml                                          |
|====================================================================================================|
|                                                                                                    |
|====================================================================================================|
|                                            Collections                                             |
|====================================================================================================|
|                                                                                                    |
|====================================================================================================|
|                                    Marvel Collection in Movies                                     |
|====================================================================================================|
|                                                                                                    |
|=================================== Validating Marvel Attributes ===================================|
|                                                                                                    |
| Validating Method: sync_mode                                                                       |
| Value: sync                                                                                        |
|                                                                                                    |
| Validating Method: trakt_list                                                                      |
| Value: https://trakt.tv/users/tetharion/lists/marvel-cinematic-universe                            |
| Trakt Error: List https://trakt.tv/users/tetharion/lists/marvel-cinematic-universe not found       |
| Traceback (most recent call last):                                                                 |
|   File "//plex_meta_manager.py", line 809, in run_collection                                       |
|     builder = CollectionBuilder(config, metadata, mapping_name, no_missing, collection_attrs, library=library) |
|   File "/modules/builder.py", line 638, in __init__                                                |
|     self._trakt(method_name, method_data)                                                          |
|   File "/modules/builder.py", line 1220, in _trakt                                                 |
|     trakt_lists = self.config.Trakt.validate_trakt(method_data, self.library.is_movie)             |
|   File "/modules/trakt.py", line 256, in validate_trakt                                            |
|     raise Failed(f"Trakt Error: No valid Trakt Lists in {values}")                                 |
| modules.util.Failed: Trakt Error: No valid Trakt Lists in ['https://trakt.tv/users/tetharion/lists/marvel-cinematic-universe'] |
|                                                                                                    |
| Trakt Error: No valid Trakt Lists in ['https://trakt.tv/users/tetharion/lists/marvel-cinematic-universe'] |
|                                                                                                    |
|====================================================================================================|
|                                     Finished Marvel Collection                                     |
|                                    Collection Run Time: 0:00:00                                    |
|====================================================================================================|
```

This is for a public list, but the private lists also have the same errors.

Running without the `-ro` flag modifies the `config.yml` as expected, but works fine when accessing `trakt` lists.

**Comment by chrisjohnson00** [comment]
I run this in kubernetes, with read only config, without problems with trakt.
What you can do is run it the container, get trakt authenticated, then copy that config file.
Now run the app in read only config mode and you should be good.

**Comment by aaronnuu** [comment]
Ahh that is a really good idea, I found a way to use ansible to only manage the part of the file that isn't being modified by using `blockinfile` but it's pretty hacky.

**Comment by meisnate12** [comment]
At the beginning of your run theres a trakt section which should have either
```
Connecting to Trakt...
Trakt Connection Successful
```
if the auth was successful or 
```
Connecting to Trakt...

Some kind of Error Message Here

Trakt Connection Failed
```
if the auth failed 

the list runs fine for me why don't you try starting the auth completely over
