### ISSUE TITLE
Error when adding actor’s shows - Plex Error: Collection ActorName not found

### ISSUE THREAD

**Issue by GsMumbo** [Kometa-Team/Kometa#92]
I remembered what the last issue I was having was! Right now I’m trying to add collections to my TV Shows library based on Actor. I tried using one of the [example user templates](https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/Glasti1/Movies.yml) but it tells me that `tmdb_person` only works on movies. 

As such I switched over to using `tmdb_actor`:

```
collections:
###########################
#    People Collections   #
###########################
  Zach Braff:
    tmdb_actor: 5367
    tmdb_actor_details: 5367
```

I picked Zach Braff as I know I have a show of his, **Alex, Inc.** 

TVDB (`328635 `): https://thetvdb.com/series/alex-inc
TMDB (`71763 `): https://www.themoviedb.org/tv/71763-alex-inc?language=en-US
Zach Braff (`5367 `): https://www.themoviedb.org/person/5367-zach-braff?language=en-US

When I run the script I see it try to map the TMDB IDs over to TVDB IDs, not find any shows, then give me this error:

`Plex Error: Collection Zach Braff not found`

Looking through the log I’m seeing `71763` in the `TVDb IDs Found` array, but it’s actually a TMDB ID. I’m thinking that’s where the problem is, it’s not translating to a TVDB ID, and thus it’s trying to pull from TVDB using a TMDB ID. I could be wrong on that though. 

I’m also not sure why it’s showing an error about not finding the collection, but I’m guessing it’s a more generic error that happens when something goes wrong?

## Log
```

|====================================================================================================|

|                                       Zach Braff Collection                                        |

|====================================================================================================|

|                                                                                                    |

| Scanning Zach Braff Collection                                                                     |

|                                                                                                    |

| Method: tmdb_actor                                                                                 |

| Value: 5367                                                                                        |

|                                                                                                    |

| Method: tmdb_actor_details                                                                         |

| Value: 5367                                                                                        |

|                                                                                                    |

| Sync Mode: sync                                                                                    |

|                                                                                                    |

| Method: tmdb_actor                                                                                 |

| Values: [5367]                                                                                     |

|                                                                                                    |

| Value: 5367                                                                                        |

| Data: 5367                                                                                         |

| Processing TMDb Actor: (5367) Zach Braff (21 Movies)                                               |

| Processing TMDb Actor: (5367) Zach Braff (31 Shows)                                                |

| TMDb IDs Found: [401, 7511, 13171, 231576, 9982, 22597, 73474, 125506, 630122, 691683, 199647, 269100, 548755, 650783, 68728, 10440, 337844, 287807, 13352, 371638, 402123] |

| TVDb IDs Found: [1834, 1900, 2342, 2518, 4556, 4573, 4589, 10448, 27213, 562, 1489, 1709, 2221, 2224, 2396, 3167, 26834, 1667, 14598, 53438, 69373, 71763, 80515, 1220, 36662, 61222, 1667, 102758, 40505, 2342, 32415] |

| No items found to add to this collection                                                           |

|                                                                                                    |

| 21 Movies Missing                                                                                  |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1834                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1900                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2342                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2518                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4556                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4573                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4589                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 10448                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 27213                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 562                                 |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1489                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1709                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2221                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2224                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2396                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 3167                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 26834                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1667                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 14598                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 53438                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 69373                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1220                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 36662                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 61222                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1667                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 102758                              |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 40505                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2342                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 32415                               |

| 2 Shows Missing                                                                                    |

|                                                                                                    |

| Method: tmdb_actor                                                                                 |

| Values: [5367]                                                                                     |

|                                                                                                    |

| Value: 5367                                                                                        |

| Data: 5367                                                                                         |

| Processing TMDb Actor: (5367) Zach Braff (21 Movies)                                               |

| Processing TMDb Actor: (5367) Zach Braff (31 Shows)                                                |

| TMDb IDs Found: [401, 7511, 13171, 231576, 9982, 22597, 73474, 125506, 630122, 691683, 199647, 269100, 548755, 650783, 68728, 10440, 337844, 287807, 13352, 371638, 402123] |

| TVDb IDs Found: [1834, 1900, 2342, 2518, 4556, 4573, 4589, 10448, 27213, 562, 1489, 1709, 2221, 2224, 2396, 3167, 26834, 1667, 14598, 53438, 69373, 71763, 80515, 1220, 36662, 61222, 1667, 102758, 40505, 2342, 32415] |

| No items found to add to this collection                                                           |

|                                                                                                    |

| 21 Movies Missing                                                                                  |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1834                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1900                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2342                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2518                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4556                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4573                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4589                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 10448                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 27213                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 562                                 |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1489                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1709                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2221                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2224                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2396                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 3167                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 26834                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1667                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 14598                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 53438                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 69373                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1220                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 36662                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 61222                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1667                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 102758                              |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 40505                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2342                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 32415                               |

| 2 Shows Missing                                                                                    |

|                                                                                                    |

| 0 Show Removed                                                                                     |

|                                                                                                    |

| Plex Error: Collection Zach Braff not found                                                        |

|                                                                                                    |

|====================================================================================================|

```

**Comment by GsMumbo** [comment]
Config still same as #90 but with caching enabled

**Comment by meisnate12** [comment]
illl look into this but what i can say off the bat is the `Plex Error: Collection Zach Braff not found` is because no item was added to the collection so it wasn't created therefore it couldn't be pulled for a metadata edit which is the last part

**Comment by meisnate12** [comment]
you were absolutely right and the fix should be in dev

**Comment by GsMumbo** [comment]
I repulled the latest dev image and it still has the incorrect IDs. Maybe the update just hasn’t hit DockerHub yet?

**Comment by meisnate12** [comment]
its there now if you want to try again

**Comment by GsMumbo** [comment]
Now that I look, for some reason the sha isn’t changing even after pulling the new image (meaning it isn’t matching DockerHub anymore). I think something funky is going on with my Docker. I’ll work on it and let you know if the fix works once I can get properly updated.

**Comment by GsMumbo** [comment]
It turns out I did have the updated image after all. Which means the issue still persists. I don’t see any additional error output in the log either:

```

|====================================================================================================|

|                                       Zach Braff Collection                                        |

|====================================================================================================|

|                                                                                                    |

| Scanning Zach Braff Collection                                                                     |

|                                                                                                    |

| Method: tmdb_actor                                                                                 |

| Value: 5367                                                                                        |

|                                                                                                    |

| Method: tmdb_actor_details                                                                         |

| Value: 5367                                                                                        |

|                                                                                                    |

| Sync Mode: sync                                                                                    |

|                                                                                                    |

| Method: tmdb_actor                                                                                 |

| Values: [5367]                                                                                     |

|                                                                                                    |

| Value: 5367                                                                                        |

| Data: 5367                                                                                         |

| Processing TMDb Actor: (5367) Zach Braff (21 Movies)                                               |

| Processing TMDb Actor: (5367) Zach Braff (31 Shows)                                                |

| TMDb IDs Found: [401, 7511, 13171, 231576, 9982, 22597, 73474, 125506, 630122, 691683, 199647, 269100, 548755, 650783, 68728, 10440, 337844, 287807, 13352, 371638, 402123] |

| TVDb IDs Found: [1834, 1900, 2342, 2518, 4556, 4573, 4589, 10448, 27213, 562, 1489, 1709, 2221, 2224, 2396, 3167, 26834, 1667, 14598, 53438, 69373, 71763, 80515, 1220, 36662, 61222, 1667, 102758, 40505, 2342, 32415] |

| No items found to add to this collection                                                           |

|                                                                                                    |

| 21 Movies Missing                                                                                  |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1834                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1900                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2342                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2518                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4556                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4573                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4589                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 10448                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 27213                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 562                                 |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1489                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1709                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2221                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2224                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2396                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 3167                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 26834                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1667                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 14598                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 53438                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 69373                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1220                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 36662                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 61222                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1667                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 102758                              |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 40505                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2342                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 32415                               |

| 2 Shows Missing                                                                                    |

|                                                                                                    |

| Method: tmdb_actor                                                                                 |

| Values: [5367]                                                                                     |

|                                                                                                    |

| Value: 5367                                                                                        |

| Data: 5367                                                                                         |

| Processing TMDb Actor: (5367) Zach Braff (21 Movies)                                               |

| Processing TMDb Actor: (5367) Zach Braff (31 Shows)                                                |

| TMDb IDs Found: [401, 7511, 13171, 231576, 9982, 22597, 73474, 125506, 630122, 691683, 199647, 269100, 548755, 650783, 68728, 10440, 337844, 287807, 13352, 371638, 402123] |

| TVDb IDs Found: [1834, 1900, 2342, 2518, 4556, 4573, 4589, 10448, 27213, 562, 1489, 1709, 2221, 2224, 2396, 3167, 26834, 1667, 14598, 53438, 69373, 71763, 80515, 1220, 36662, 61222, 1667, 102758, 40505, 2342, 32415] |

| No items found to add to this collection                                                           |

|                                                                                                    |

| 21 Movies Missing                                                                                  |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1834                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1900                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2342                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2518                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4556                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4573                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 4589                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 10448                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 27213                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 562                                 |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1489                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1709                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2221                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2224                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2396                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 3167                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 26834                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1667                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 14598                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 53438                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 69373                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1220                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 36662                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 61222                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 1667                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 102758                              |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 40505                               |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 2342                                |

| TVDb Error: Could not find a TVDb Series using TVDb Series ID: 32415                               |

| 2 Shows Missing                                                                                    |

|                                                                                                    |

| 0 Show Removed                                                                                     |

|                                                                                                    |

| Plex Error: Collection Zach Braff not found                                                        |

|                                                                                                    |

|====================================================================================================|

```

**Comment by meisnate12** [comment]
ok fix is in i had to fix it in two spots one for actors specifically and the other for all the rest haha I fixed it for all the rest but not for actors it should be good now

**Comment by GsMumbo** [comment]
I was just about to comment saying you missed one on line 117! Pulling the new image now :)

**Comment by GsMumbo** [comment]
It’s still pulling the wrong IDs. I followed the functions up to `convert_from_tmdb` and I haven’t seen any issues yet. I’m thinking at this point maybe it’s that conversion itself that’s not working properly?

**Comment by meisnate12** [comment]
can you try updating the image again the collection is finding the right IDs for me

btw having both `tmdb_actor_details` and `tmdb_actor` is redundant you only need `tmdb_actor_details`

```
|====================================================================================================|
|                                       Zach Braff Collection                                        |
|====================================================================================================|
|                                                                                                    |
| Scanning Zach Braff Collection                                                                     |
|                                                                                                    |
| Method: tmdb_actor_details                                                                         |
| Value: 5367                                                                                        |
|                                                                                                    |
| Sync Mode: append                                                                                  |
|                                                                                                    |
| Method: tmdb_actor                                                                                 |
| Values: [5367]                                                                                     |
|                                                                                                    |
| Value: 5367                                                                                        |
| Data: 5367                                                                                         |
| TMDb Error: No TVDb ID found for TMDb ID 14598                                                     |
| TMDb Error: No TVDb ID found for TMDb ID 80515                                                     |
| TMDb Error: No TVDb ID found for TMDb ID 36662                                                     |
| Processing TMDb Actor: (5367) Zach Braff (21 Movies)                                               |
| Processing TMDb Actor: (5367) Zach Braff (28 Shows)                                                |
| TMDb IDs Found: [401, 7511, 13171, 231576, 9982, 22597, 73474, 125506, 630122, 691683, 199647, 269100, 548755, 650783, 68728, 10440, 337844, 287807, 13352, 371638, 402123] |
| TVDb IDs Found: [80652, 72146, 78560, 70336, 76156, 76737, 72173, 76214, 77515, 72194, 71998, 70708, 72104, 71256, 72268, 77924, 74781, 76177, 267172, 323843, 328635, 80660, 282254, 76177, 291758, 253279, 78560, 194751] |
| Zach Braff Collection | = | BoJack Horseman                                                        |
| 1 Show Processed                                                                                   |
|                                                                                                    |
| Zach Braff Collection | ? | Garden State (TMDb: 401)                                               |
| Zach Braff Collection | ? | The Last Kiss (TMDb: 7511)                                             |
| Zach Braff Collection | ? | The Ex (TMDb: 13171)                                                   |
| Zach Braff Collection | ? | Wish I Was Here (TMDb: 231576)                                         |
| Zach Braff Collection | ? | Chicken Little (TMDb: 9982)                                            |
| Zach Braff Collection | ? | The Broken Hearts Club: A Romantic Comedy (TMDb: 22597)                |
| Zach Braff Collection | ? | The High Cost of Living (TMDb: 73474)                                  |
| Zach Braff Collection | ? | Getting to Know You (TMDb: 125506)                                     |
| Zach Braff Collection | ? | I’m Still Here: Real Diaries of Young People Who Lived During the Holocaust (TMDb: 630122) |
| Zach Braff Collection | ? | Cheaper by the Dozen (TMDb: 691683)                                    |
| Zach Braff Collection | ? | The Color of Time (TMDb: 199647)                                       |
| Zach Braff Collection | ? | Video Games: The Movie (TMDb: 269100)                                  |
| Zach Braff Collection | ? | Percy (TMDb: 548755)                                                   |
| Zach Braff Collection | ? | The Comeback Trail (TMDb: 650783)                                      |
| Zach Braff Collection | ? | Oz the Great and Powerful (TMDb: 68728)                                |
| Zach Braff Collection | ? | Manhattan Murder Mystery (TMDb: 10440)                                 |
| Zach Braff Collection | ? | In Dubious Battle (TMDb: 337844)                                       |
| Zach Braff Collection | ? | Blue Moon (TMDb: 287807)                                               |
| Zach Braff Collection | ? | It's a Very Merry Muppet Christmas Movie (TMDb: 13352)                 |
| Zach Braff Collection | ? | The Disaster Artist (TMDb: 371638)                                     |
| Zach Braff Collection | ? | Lennon or McCartney (TMDb: 402123)                                     |
| 21 Movies Missing                                                                                  |
| Zach Braff Collection | ? | Friday Night with Jonathan Ross (TVDB: 80652)                          |
| Zach Braff Collection | ? | LIVE with Kelly and Ryan (TVDB: 72146)                                 |
| Zach Braff Collection | ? | Clone High (TVDB: 78560)                                               |
| Zach Braff Collection | ? | The Tonight Show with Jay Leno (TVDB: 70336)                           |
| Zach Braff Collection | ? | Scrubs (TVDB: 76156)                                                   |
| Zach Braff Collection | ? | Late Night with Conan O'Brien (TVDB: 76737)                            |
| Zach Braff Collection | ? | Arrested Development (TVDB: 72173)                                     |
| Zach Braff Collection | ? | The Baby-Sitters Club (TVDB: 76214)                                    |
| Zach Braff Collection | ? | The Late Late Show with Craig Kilborn (TVDB: 77515)                    |
| Zach Braff Collection | ? | The Ellen DeGeneres Show (TVDB: 72194)                                 |
| Zach Braff Collection | ? | Jimmy Kimmel Live! (TVDB: 71998)                                       |
| Zach Braff Collection | ? | Today (TVDB: 70708)                                                    |
| Zach Braff Collection | ? | The View (TVDB: 72104)                                                 |
| Zach Braff Collection | ? | The Daily Show (TVDB: 71256)                                           |
| Zach Braff Collection | ? | Punk'd (TVDB: 72268)                                                   |
| Zach Braff Collection | ? | The Early Show (TVDB: 77924)                                           |
| Zach Braff Collection | ? | TRL (TVDB: 74781)                                                      |
| Zach Braff Collection | ? | Saturday Night Live (TVDB: 76177)                                      |
| Zach Braff Collection | ? | Circus HalliGalli (TVDB: 267172)                                       |
| Zach Braff Collection | ? | Bill Nye Saves the World (TVDB: 323843)                                |
| Zach Braff Collection | ? | Alex, Inc. (TVDB: 328635)                                              |
| Zach Braff Collection | ? | The Graham Norton Show (TVDB: 80660)                                   |
| Zach Braff Collection | ? | Saturday Night Live (TVDB: 76177)                                      |
| Zach Braff Collection | ? | Off Camera with Sam Jones (TVDB: 291758)                               |
| Zach Braff Collection | ? | The Exes (TVDB: 253279)                                                |
| Zach Braff Collection | ? | Clone High (TVDB: 78560)                                               |
| Zach Braff Collection | ? | Conan (2010) (TVDB: 194751)                                            |
| 27 Shows Missing                                                                                   |
|                                                                                                    |
| Detail: tmdb_actor_details updated Collection Summary                                              |
| {'summary.value': 'Zachary Israel "Zach" Braff (born April 6, 1975 in South orange, New Jersey) is an American actor, screenwriter, producer, and director. Braff first became known in 2001 for his role as Dr. John Dorian on the TV series Scrubs, which earned him his first Emmy nomination. Braff remained working on Scrubs for eight years, until he announced his departure as an actor, his last episode airing in December 2009. Braff has, however, taken an executive producer\'s role on the series.\n\nIn 2004, Braff made his directorial debut with Garden State, a coming of age film. Braff returned to his home state of New Jersey to shoot the film, which was produced on a budget of $2.5 million. The film made over $35 million at the box office as well as profiting from DVD sales, and was praised by critics, giving Braff his first financial success and critical acclaim in film work. Braff wrote the film, starred in it, and selected and produced the soundtrack record, for which he won a Grammy Award for Best Soundtrack Album in 2005.\n\nBraff is also known for starring in the films The Last Kiss and The Ex, and for his vocal work on Chicken Little. In 1993, he had a supporting role in Woody Allen\'s Manhattan Murder Mystery – a role that would mark his film debut. Braff states that he will continue to write and direct films in the coming years.', 'summary.locked': 1} |
| Details: have been updated                                                                         |
| Detail: tmdb_actor_details updated collection poster to [URL] https://image.tmdb.org/t/p/original/wUAj6juL6HErqEJ1GtuI63rbVea.jpg |
|                                                                                                    |
| No background to update                                                                            |
|                                                                                                    |
```

**Comment by GsMumbo** [comment]
It worked! I’m not sure what changed, but everything is mapping correctly now. I even ran a few combinations to see what could have been causing it to fail last night:

```

collections:
###########################
#    People Collections   #
###########################
  Zach Braff:
    # tmdb_actor: 5367
    tmdb_actor_details: 5367
  David Tennant:
    tmdb_actor: 20049
    # tmdb_actor_details: 20049
  Zachary Levi:
    tmdb_actor: 69899
    tmdb_actor_details: 69899

```

Every single one worked properly. So thank you again! I’ll be using `tmdb_actor_details` going forward.

Side question, is tmdb the only source that can pull in images, summaries, details, etc? Can you pull in that information from Trakt, TVDB, etc?

**Comment by meisnate12** [comment]
i might be able to from tvdb i thought trakt just pulled from tmdb tom be honest

**Comment by GsMumbo** [comment]
Trakt pulls from TMDB for metadata, but not for custom lists. Those are user-made and have their own custom descriptions and sort orders. For example with Cosmic Horror, there are two lists I keyed in on:

https://trakt.tv/users/patchwrks/lists/cosmic?sort=released,asc - This one has a fairly lengthy multi-line description which can be a pain to enter manually using YAML. Plus it takes up a lot of space in the .yml file.

https://trakt.tv/users/willard_h/lists/cosmic-horror-best-to-worst?sort=rank,asc - This one doesn’t have a description but does have a custom sort that is integral to the list.

This is a bit off topic from the original issue, so if it’s something you’d be open to I can create a new issue for a feature request. It’s also a smaller ask that mainly makes things a bit easier and cleaner. In the few days I’ve been using this script I can’t tell you how excited I’ve been at the sheer power of it. Major props!

**Comment by meisnate12** [comment]
I might be able to get the trakt list descriptions I'll see. I'm working on seeing if I can have trakt lists limit and sort but unfortunately that wouldn't translate to plex until custom collection sort order is a thing. Once it is I'll be sure to add it in

**Comment by meisnate12** [comment]
I've added the collection builders: `trakt_list_details`, `tvdb_list_details`, `tvdb_show_details`, and `tvdb_movie_details`. 
I've added the collection details: `trakt_description`, `tvdb_summary`, `tvdb_description`, `tvdb_poster`, and `tvdb_background`.
